CREATE DATABASE TTWS;
USE TTWS;
CREATE TABLE USER (
ID_USER INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASS VARCHAR(10) NOT NULL,
PRIMARY KEY (ID_USER)
);


CREATE TABLE FOLIO
(
ID_FOLIO INT NOT NULL,
BEGINNIG VARCHAR(100) NOT NULL,
DESTINATION VARCHAR(100) NOT NULL,
CURRENT_STATUS CHAR(3) NOT NULL,
PRIMARY KEY (ID_FOLIO)
);


CREATE TABLE FOLLOWUP
(
ID_FOLIO INT NOT NULL,
ID_USER INT NOT NULL
);
